name: Continuous Integration Workflow

on:
  push:
    branches:
      - main
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm i
      
    - name: run linter
      run: npm run lint

    - name: run code coverage
      run: npx jest --coverage --passWithNoTests

    - name: Step 1 - Create a temporary artifact downloads folder
      run: mkdir downloads
      
    - name: step 2 - Add artifacts to publish to the temp folder
      run: cp -R node_modules downloads && cp index.js downloads/index.js  && cp package.json downloads/package.json
  
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: downloads     
        
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
