name: Continuous Integration Workflow

on:
  push:
    branches:
      - main
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm i
      
    - name: run linter
      run: npm run lint

    - name: run code coverage
      run: npx jest --coverage --passWithNoTests

    - name: step 2 - Add artifacts to publish to the temp folder
      run: zip -r artifact.zip .
        
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: build
        path: artifact.zip   
        
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v3
    
    - name: Debug
      run: ls -al ${{ runner.temp }}
      
    - name: unzip zip file
      run: unzip build.zip -d .
    
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: icydc
        publish-profile: ${{ secrets.AZURE_PROFILE }}
