name: Deploy

on:
  workflow_run:
    workflows: ["Continuous Integration Workflow"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: assets-for-download 

    - name: Display structure of downloaded files
      run: ls -R
    
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: helloworld
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
